### ISSUE TITLE
HBG Do not work

### ISSUE THREAD

**Issue by responsiveIT-repo** [Synecdoche1/Void-NX#4]
Hi and thanks for your bundle. Unfortuznatly, once launching HBG, It display the same error message as with kosmos (red screen where you can only exit or uninstall kosmos) ... 

Thanks !

**Comment by Synecdoche1** [comment]
Finally got a chance to find an HBG file to test it, I have fixed the issues on a clean SD Card and verified that HBG does now in fact work.

**Comment by responsiveIT-repo** [comment]
Thanks for the quick answer!
